### ISSUE TITLE
Web Admin Portal Isn't Working

### ISSUE THREAD

**Issue by dudleycodes** [LacledesLAN/gamesvr-ut2004-freeplay#1]
Despite being enabled; navigating to port 8888 doesn't show the web admin interface.

**Comment by mattburchett** [comment]
This appears to be working correctly when I tried running the container. 

I built the container using: 
`docker build -t ut2004 -f linux.Dockerfile .`

I created the container using the following params:
`docker run --name=ut2004 -d --net=host ut2004 ./ucc-bin server CTF-January?AdminName=testuser?AdminPassword=12345 ini=UT2004.ini`

I confirmed I was able to access the portal using netcat: 

`
docker run --name=ut2004 -d --net=host ut2004 ./ucc-bin server CTF-January?AdminName=testuser?AdminPassword=12345 ini=UT2004.in
`

I attempted login with the username/password I specified in the AdminName/AdminPassword vars: 

```bash
$ curl -Lku testuser:12345 172.19.0.218:8888
<html>
 <head><TITLE>Lacledes LAN UT2004 Deathmatch Server - Unreal Tournament 2004 - Web Admin</TITLE>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
 </head>
 <frameset rows="125,*" cols="*" frameborder="No" framespacing="0" border="0">
  <frame src="mainmenu?Group=currentframe" name="menu" noresize frameborder="0" marginheight="0" scrolling="no" framespacing="0">
  <frame src="currentframe" name="menumain" scrolling="no" frameborder="no" noresize framespacing="0" marginheight="0">
 </frameset>
 <noframes>
  <body bgcolor="#FFFFFF">This Server Requires Frames.</body>
 </noframes>
</html>
```

And to confirm this actually authenticating, I gave it a bad password instead:

```bash
$ curl -Lku testuser:123456 172.19.0.218:8888
<TITLE>401 Unauthorized</TITLE><H1>401 Unauthorized</H1>
```

**Comment by dudleycodes** [comment]
Confirmed working; closing issue
